export const allChains = [
    {
      "name": "eth-mainnet",
      "chain_id": "1",
      "is_testnet": false,
      "db_schema_name": "chain_eth_mainnet",
      "label": "Ethereum Mainnet",
      "category_label": "Ethereum",
      "logo_url": "https://www.datocms-assets.com/86369/1669653891-eth.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669619544-ethereum.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669619533-ethereum.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "eth-goerli",
      "chain_id": "5",
      "is_testnet": true,
      "db_schema_name": "chain_eth_goerli",
      "label": "Ethereum Goerli Testnet",
      "category_label": "Ethereum",
      "logo_url": "https://www.datocms-assets.com/86369/1669653891-eth.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669619544-ethereum.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669619533-ethereum.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "matic-mainnet",
      "chain_id": "137",
      "is_testnet": false,
      "db_schema_name": "chain_matic_mainnet",
      "label": "Polygon Mainnet",
      "category_label": "Polygon",
      "logo_url": "https://www.datocms-assets.com/86369/1677870347-property-1-polygon-zkevm-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1677870457-property-1-polygon-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1677870452-property-1-polygon-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "matic-mumbai",
      "chain_id": "80001",
      "is_testnet": true,
      "db_schema_name": "chain_matic_mumbai",
      "label": "Polygon Testnet Mumbai",
      "category_label": "Polygon",
      "logo_url": "https://www.datocms-assets.com/86369/1677870347-property-1-polygon-zkevm-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1677870457-property-1-polygon-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1677870452-property-1-polygon-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "avalanche-mainnet",
      "chain_id": "43114",
      "is_testnet": false,
      "db_schema_name": "chain_avalanche_mainnet",
      "label": "Avalanche C-Chain Mainnet",
      "category_label": "Avalanche",
      "logo_url": "https://www.datocms-assets.com/86369/1686152918-avalanche-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1686152986-avalanche-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1686152997-avalanche-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "avalanche-testnet",
      "chain_id": "43113",
      "is_testnet": true,
      "db_schema_name": "chain_avalanche_testnet",
      "label": "Avalanche Fuji Testnet",
      "category_label": "Avalanche",
      "logo_url": "https://www.datocms-assets.com/86369/1686152918-avalanche-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1686152986-avalanche-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1686152997-avalanche-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "bsc-mainnet",
      "chain_id": "56",
      "is_testnet": false,
      "db_schema_name": "chain_bsc_mainnet",
      "label": "BNB Smart Chain",
      "category_label": "Binance",
      "logo_url": "https://www.datocms-assets.com/86369/1670003808-binance-smart-chain-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670003836-biance-smart-chain-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670003837-biance-smart-chain-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "bsc-testnet",
      "chain_id": "97",
      "is_testnet": true,
      "db_schema_name": "chain_bsc_testnet",
      "label": "BNB Smart Chain Testnet",
      "category_label": "Binance",
      "logo_url": "https://www.datocms-assets.com/86369/1670003808-binance-smart-chain-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670003836-biance-smart-chain-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670003837-biance-smart-chain-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "moonbeam-mainnet",
      "chain_id": "1284",
      "is_testnet": false,
      "db_schema_name": "chain_moonbeam_mainnet",
      "label": "Moonbeam Mainnet",
      "category_label": "Moonbeam",
      "logo_url": "https://www.datocms-assets.com/86369/1669924204-moonbeam.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669924233-moonbeam.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669924256-moonbeam-1.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "moonbeam-moonbase-alpha",
      "chain_id": "1287",
      "is_testnet": true,
      "db_schema_name": "chain_moonbeam_moonbase_alpha",
      "label": "Moonbeam Moonbase Alpha",
      "category_label": "Moonbeam",
      "logo_url": "https://www.datocms-assets.com/86369/1669924204-moonbeam.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669924233-moonbeam.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669924256-moonbeam-1.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "moonbeam-moonriver",
      "chain_id": "1285",
      "is_testnet": false,
      "db_schema_name": "chain_moonbeam_moonriver",
      "label": "Moonbeam Moonriver",
      "category_label": "Moonbeam",
      "logo_url": "https://www.datocms-assets.com/86369/1669924101-moonriver.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669924133-moonriver.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669924155-moonriver-1.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "rsk-mainnet",
      "chain_id": "30",
      "is_testnet": false,
      "db_schema_name": "chain_rsk_mainnet",
      "label": "RSK Mainnet",
      "category_label": "RSK",
      "logo_url": "https://www.datocms-assets.com/86369/1675107803-property-1-rootstock-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1675107791-property-1-rootstock-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1675107795-property-1-rootstock-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "rsk-testnet",
      "chain_id": "31",
      "is_testnet": true,
      "db_schema_name": "chain_rsk_testnet",
      "label": "RSK Testnet",
      "category_label": "RSK",
      "logo_url": "https://www.datocms-assets.com/86369/1675107803-property-1-rootstock-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1675107791-property-1-rootstock-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1675107795-property-1-rootstock-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "arbitrum-mainnet",
      "chain_id": "42161",
      "is_testnet": false,
      "db_schema_name": "chain_arbitrum_mainnet",
      "label": "Arbitrum Mainnet",
      "category_label": "Arbitrum",
      "logo_url": "https://www.datocms-assets.com/86369/1686072650-arbitrum-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669925049-arbitrum-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669925028-arbitrum.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "arbitrum-goerli",
      "chain_id": "421613",
      "is_testnet": true,
      "db_schema_name": "chain_arbitrum_goerli",
      "label": "Arbitrum Goerli",
      "category_label": "Arbitrum",
      "logo_url": "https://www.datocms-assets.com/86369/1686072650-arbitrum-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669925049-arbitrum-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669925028-arbitrum.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "arbitrum-nova-mainnet",
      "chain_id": "42170",
      "is_testnet": false,
      "db_schema_name": "chain_arbitrum_nova_mainnet",
      "label": "Arbitrum Nova Mainnet",
      "category_label": "Arbitrum",
      "logo_url": "https://www.datocms-assets.com/86369/1675883705-property-1-nova-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1675883711-property-1-nova-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1675883708-property-1-nova-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "fantom-mainnet",
      "chain_id": "250",
      "is_testnet": false,
      "db_schema_name": "chain_fantom_mainnet",
      "label": "Fantom Opera",
      "category_label": "Fantom",
      "logo_url": "https://www.datocms-assets.com/86369/1669925386-fantom.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669925336-fantom.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669925359-fantom-1.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "fantom-testnet",
      "chain_id": "4002",
      "is_testnet": true,
      "db_schema_name": "chain_fantom_testnet",
      "label": "Fantom Testnet",
      "category_label": "Fantom",
      "logo_url": "https://www.datocms-assets.com/86369/1669925386-fantom.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669925336-fantom.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669925359-fantom-1.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "palm-mainnet",
      "chain_id": "11297108109",
      "is_testnet": false,
      "db_schema_name": "chain_palm_mainnet",
      "label": "Palm Mainnet",
      "category_label": "Palm",
      "logo_url": "https://www.datocms-assets.com/86369/1669930692-palm.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669930756-palm-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669930724-palm.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "palm-testnet",
      "chain_id": "11297108099",
      "is_testnet": true,
      "db_schema_name": "chain_palm_testnet",
      "label": "Palm Testnet",
      "category_label": "Palm",
      "logo_url": "https://www.datocms-assets.com/86369/1669930692-palm.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669930756-palm-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669930724-palm.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "nervos-godwoken-mainnet",
      "chain_id": "71402",
      "is_testnet": false,
      "db_schema_name": "chain_nervos_godwoken_mainnet",
      "label": "Nervos Godwoken Mainnet",
      "category_label": "Nervos",
      "logo_url": "https://www.datocms-assets.com/86369/1669931443-godwoken.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669931401-godwoken.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669931425-godwoken-1.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "nervos-godwoken-testnet",
      "chain_id": "71401",
      "is_testnet": true,
      "db_schema_name": "chain_nervos_godwoken_testnet",
      "label": "Nervos Godwoken Testnet",
      "category_label": "Nervos",
      "logo_url": "https://www.datocms-assets.com/86369/1669931443-godwoken.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669931401-godwoken.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669931425-godwoken-1.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "axie-mainnet",
      "chain_id": "2020",
      "is_testnet": false,
      "db_schema_name": "chain_axie_mainnet",
      "label": "Axie Mainnet",
      "category_label": "Axie",
      "logo_url": "https://www.datocms-assets.com/86369/1669931671-axie.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669931714-ronin-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669931693-ronin.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "evmos-mainnet",
      "chain_id": "9001",
      "is_testnet": false,
      "db_schema_name": "chain_evmos_mainnet",
      "label": "EVMOS Mainnet",
      "category_label": "EVMOS",
      "logo_url": "https://www.datocms-assets.com/86369/1669931869-evmos.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669931911-evmos-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669931890-evmos.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "evmos-testnet",
      "chain_id": "9000",
      "is_testnet": true,
      "db_schema_name": "chain_evmos_testnet",
      "label": "EVMOS Testnet",
      "category_label": "EVMOS",
      "logo_url": "https://www.datocms-assets.com/86369/1669931869-evmos.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669931911-evmos-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669931890-evmos.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "astar-mainnet",
      "chain_id": "592",
      "is_testnet": false,
      "db_schema_name": "chain_astar_mainnet",
      "label": "Astar Mainnet",
      "category_label": "Astar",
      "logo_url": "https://www.datocms-assets.com/86369/1669932076-astar-main.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669932222-astar-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669932206-astar.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "astar-shiden",
      "chain_id": "336",
      "is_testnet": false,
      "db_schema_name": "chain_astar_shiden",
      "label": "Astar Shiden",
      "category_label": "Astar",
      "logo_url": "https://www.datocms-assets.com/86369/1670007105-shiden.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670007111-shiden-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670007109-shiden.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "harmony-mainnet",
      "chain_id": "1666600000",
      "is_testnet": false,
      "db_schema_name": "chain_harmony_mainnet",
      "label": "Harmony Mainnet",
      "category_label": "Harmony",
      "logo_url": "https://www.datocms-assets.com/86369/1669932573-harmony.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669932617-harmony-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669932596-harmony.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "harmony-testnet",
      "chain_id": "1666700000",
      "is_testnet": true,
      "db_schema_name": "chain_harmony_testnet",
      "label": "Harmony Testnet",
      "category_label": "Harmony",
      "logo_url": "https://www.datocms-assets.com/86369/1669932573-harmony.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669932617-harmony-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669932596-harmony.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "cronos-mainnet",
      "chain_id": "25",
      "is_testnet": false,
      "db_schema_name": "chain_cronos_mainnet",
      "label": "Cronos Mainnet",
      "category_label": "Cronos",
      "logo_url": "https://www.datocms-assets.com/86369/1669933123-cronos.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669933090-cronos.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669933104-cronos-1.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "aurora-mainnet",
      "chain_id": "1313161554",
      "is_testnet": false,
      "db_schema_name": "chain_aurora_mainnet",
      "label": "Aurora Mainnet",
      "category_label": "Aurora",
      "logo_url": "https://www.datocms-assets.com/86369/1669933298-aurora.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669933692-aurora-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669933689-aurora-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "aurora-testnet",
      "chain_id": "1313161555",
      "is_testnet": true,
      "db_schema_name": "chain_aurora_testnet",
      "label": "Aurora Testnet",
      "category_label": "Aurora",
      "logo_url": "https://www.datocms-assets.com/86369/1669933298-aurora.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669933692-aurora-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669933689-aurora-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "emerald-paratime-mainnet",
      "chain_id": "42262",
      "is_testnet": false,
      "db_schema_name": "chain_emerald_paratime_mainnet",
      "label": "Oasis Emerald ParaTime Mainnet",
      "category_label": "Oasis",
      "logo_url": "https://www.datocms-assets.com/86369/1669933877-oasis.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669933853-oasis-1.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669933835-oasis.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "defi-kingdoms-mainnet",
      "chain_id": "53935",
      "is_testnet": false,
      "db_schema_name": "chain_defi_kingdoms_mainnet",
      "label": "DeFi Kingdoms Mainnet",
      "category_label": "Avalanche",
      "logo_url": "https://www.datocms-assets.com/86369/1670009063-defi-kingdoms-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670009081-defi-kingdoms-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670009079-defi-kingdoms-colour.png",
      "is_appchain": true,
      "appchain_of": {
        "name": "avalanche-mainnet",
        "chain_id": "43114",
        "is_testnet": false,
        "db_schema_name": "chain_avalanche_mainnet",
        "label": "Avalanche C-Chain Mainnet",
        "category_label": "Avalanche",
        "logo_url": "https://www.datocms-assets.com/86369/1686152918-avalanche-icon-white.svg",
        "black_logo_url": "https://www.datocms-assets.com/86369/1686152986-avalanche-white.png",
        "white_logo_url": "https://www.datocms-assets.com/86369/1686152997-avalanche-colour.png",
        "is_appchain": false,
        "appchain_of": null
      }
    },
    {
      "name": "swimmer-mainnet",
      "chain_id": "73772",
      "is_testnet": false,
      "db_schema_name": "chain_swimmer_mainnet",
      "label": "Swimmer Mainnet",
      "category_label": "Avalanche",
      "logo_url": "https://www.datocms-assets.com/86369/1670009284-swimmer-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670009294-swimmer-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670009291-swimmer-colour.png",
      "is_appchain": true,
      "appchain_of": {
        "name": "avalanche-mainnet",
        "chain_id": "43114",
        "is_testnet": false,
        "db_schema_name": "chain_avalanche_mainnet",
        "label": "Avalanche C-Chain Mainnet",
        "category_label": "Avalanche",
        "logo_url": "https://www.datocms-assets.com/86369/1686152918-avalanche-icon-white.svg",
        "black_logo_url": "https://www.datocms-assets.com/86369/1686152986-avalanche-white.png",
        "white_logo_url": "https://www.datocms-assets.com/86369/1686152997-avalanche-colour.png",
        "is_appchain": false,
        "appchain_of": null
      }
    },
    {
      "name": "boba-mainnet",
      "chain_id": "288",
      "is_testnet": false,
      "db_schema_name": "chain_boba_mainnet",
      "label": "Boba Mainnet",
      "category_label": "Boba",
      "logo_url": "https://www.datocms-assets.com/86369/1669934133-boba.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669934095-boba.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669934111-boba-1.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "boba-avalanche-mainnet",
      "chain_id": "43288",
      "is_testnet": false,
      "db_schema_name": "chain_boba_avalanche_mainnet",
      "label": "Boba Avalanche Mainnet",
      "category_label": "Boba",
      "logo_url": "https://www.datocms-assets.com/86369/1670011756-boba-avax-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670011774-boba-avax-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670011765-boba-avax-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "boba-bobabeam-mainnet",
      "chain_id": "1294",
      "is_testnet": false,
      "db_schema_name": "chain_boba_bobabeam_mainnet",
      "label": "Boba Bobabeam Mainnet",
      "category_label": "Boba",
      "logo_url": "https://www.datocms-assets.com/86369/1670012081-boba-moonbeam-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670012094-boba-moonbeam-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670012092-boba-moonbeam-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "boba-avalanche-testnet",
      "chain_id": "4328",
      "is_testnet": true,
      "db_schema_name": "chain_boba_avalanche_testnet",
      "label": "Boba Avalanche Testnet",
      "category_label": "Boba",
      "logo_url": "https://www.datocms-assets.com/86369/1670011756-boba-avax-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670011774-boba-avax-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670011765-boba-avax-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "boba-rinkeby-testnet",
      "chain_id": "28",
      "is_testnet": true,
      "db_schema_name": "chain_boba_rinkeby_testnet",
      "label": "Boba Rinkeby Testnet",
      "category_label": "Boba",
      "logo_url": "https://www.datocms-assets.com/86369/1669934133-boba.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1669934095-boba.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1669934111-boba-1.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "boba-bobabase-testnet",
      "chain_id": "1297",
      "is_testnet": true,
      "db_schema_name": "chain_boba_bobabase_testnet",
      "label": "Boba Bobabase Testnet",
      "category_label": "Boba",
      "logo_url": "https://www.datocms-assets.com/86369/1670012081-boba-moonbeam-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670012094-boba-moonbeam-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670012092-boba-moonbeam-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "boba-bnb-mainnet",
      "chain_id": "56288",
      "is_testnet": false,
      "db_schema_name": "chain_boba_bnb_mainnet",
      "label": "Boba BNB Mainnet",
      "category_label": "Boba",
      "logo_url": "https://www.datocms-assets.com/86369/1670012270-boba-bnb-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670012287-boba-bnb-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670012283-boba-bnb-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "boba-bnb-testnet",
      "chain_id": "9728",
      "is_testnet": true,
      "db_schema_name": "chain_boba_bnb_testnet",
      "label": "Boba BNB Testnet",
      "category_label": "Boba",
      "logo_url": "https://www.datocms-assets.com/86369/1670012270-boba-bnb-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670012287-boba-bnb-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670012283-boba-bnb-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "skale-omnus",
      "chain_id": "1026062157",
      "is_testnet": false,
      "db_schema_name": "chain_skale_omnus",
      "label": "Omnus",
      "category_label": "SKALE",
      "logo_url": "https://www.datocms-assets.com/86369/1670526599-omnus-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670526606-omnus-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670526603-omnus-colour.png",
      "is_appchain": true,
      "appchain_of": null
    },
    {
      "name": "skale-razor",
      "chain_id": "278611351",
      "is_testnet": false,
      "db_schema_name": "chain_skale_razor",
      "label": "Razor",
      "category_label": "SKALE",
      "logo_url": "https://www.datocms-assets.com/86369/1670525389-razor-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670525400-razor-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670525395-razor-colour.png",
      "is_appchain": true,
      "appchain_of": null
    },
    {
      "name": "skale-europa",
      "chain_id": "2046399126",
      "is_testnet": false,
      "db_schema_name": "chain_skale_europa",
      "label": "Europa",
      "category_label": "SKALE",
      "logo_url": "https://www.datocms-assets.com/86369/1675460694-property-1-ruby-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1675460682-property-1-ruby-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1675460707-property-1-ruby-colour.png",
      "is_appchain": true,
      "appchain_of": null
    },
    {
      "name": "skale-calypso",
      "chain_id": "1564830818",
      "is_testnet": false,
      "db_schema_name": "chain_skale_calypso",
      "label": "SKALE Calypso",
      "category_label": "SKALE",
      "logo_url": "https://www.datocms-assets.com/86369/1670523862-calypso-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670523872-calypso-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670523869-calypso-colour.png",
      "is_appchain": true,
      "appchain_of": null
    },
    {
      "name": "gather-mainnet",
      "chain_id": "192837465",
      "is_testnet": false,
      "db_schema_name": "chain_gather_mainnet",
      "label": "Gather Mainnet",
      "category_label": "Gather",
      "logo_url": "https://www.datocms-assets.com/86369/1670285457-gather-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670285465-gather-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670285461-gather-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "gather-testnet",
      "chain_id": "356256156",
      "is_testnet": true,
      "db_schema_name": "chain_gather_testnet",
      "label": "Gather Testnet",
      "category_label": "Gather",
      "logo_url": "https://www.datocms-assets.com/86369/1670285457-gather-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670285465-gather-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670285461-gather-colour.png",
      "is_appchain": false,
      "appchain_of": null
    },
    {
      "name": "covalent-internal-network-v1",
      "chain_id": "1131378225",
      "is_testnet": false,
      "db_schema_name": "chain_covint1",
      "label": "Covalent Internal V1",
      "category_label": "Covalent",
      "logo_url": "https://www.datocms-assets.com/86369/1670020705-covalent-icon-white.svg",
      "black_logo_url": "https://www.datocms-assets.com/86369/1670020716-covalent-white.png",
      "white_logo_url": "https://www.datocms-assets.com/86369/1670020711-covalent-colour.png",
      "is_appchain": false,
      "appchain_of": null
    }
  ]